const fs = require('fs');

const newSection = `<section class="py-28 px-6"><div class="text-center mb-20 reveal"><p class="font-script text-4xl md:text-5xl text-gold text-glow">with blessings of</p><h2 class="font-display text-4xl md:text-6xl gold-text mt-2 uppercase tracking-widest text-glow">Our Families</h2></div><div class="max-w-5xl mx-auto grid md:grid-cols-2 gap-8"><div class="reveal glass-temple ornate-border rounded-2xl p-10 text-center" style="transition-delay:0ms"><div class="relative inline-block mx-auto" style="width:56px;height:67.2px"><div class="absolute left-1/2 -translate-x-1/2 rounded-full animate-pulse-glow" style="top:10%;width:33.6px;height:33.6px;background:radial-gradient(circle, oklch(0.95 0.15 70 / 0.7), transparent 70%);filter:blur(8px)"></div><img src="https://invite-charm-58.lovable.app/assets/diya-CP3LI3Pv.png" alt="" width="56" height="56" class="relative z-10 animate-flame" style="width:56px;height:auto"></div><p class="mt-4 text-[10px] tracking-[0.4em] uppercase text-gold">Bride's Family</p><p class="font-tamil-serif text-xl text-ivory mt-8">ஸ்ரீமான். T. சீனிவாசன்</p><p class="font-tamil-serif text-xl text-ivory mt-3">ஸ்ரீமதி. N. சேஷகிரி (எ) சந்திரா</p></div><div class="reveal glass-temple ornate-border rounded-2xl p-10 text-center" style="transition-delay:100ms"><div class="relative inline-block mx-auto" style="width:56px;height:67.2px"><div class="absolute left-1/2 -translate-x-1/2 rounded-full animate-pulse-glow" style="top:10%;width:33.6px;height:33.6px;background:radial-gradient(circle, oklch(0.95 0.15 70 / 0.7), transparent 70%);filter:blur(8px)"></div><img src="https://invite-charm-58.lovable.app/assets/diya-CP3LI3Pv.png" alt="" width="56" height="56" class="relative z-10 animate-flame" style="width:56px;height:auto"></div><p class="mt-4 text-[10px] tracking-[0.4em] uppercase text-gold">Groom's Family</p><p class="font-tamil-serif text-xl text-ivory mt-8">ஸ்ரீமான். S. பூபாலன்</p><p class="font-tamil-serif text-xl text-ivory mt-3">ஸ்ரீமதி. J. ரேவதி</p><div class="mt-8 pt-6 border-t border-gold/15"><p class="font-tamil-serif text-lg text-ivory">தம்பி. B. மனோஜ்குமார்</p><p class="text-[11px] tracking-[0.15em] text-sandal/60 mt-1 uppercase font-serif">B.VOC., (IT), M.B.A., DCM.,</p><p class="font-tamil-serif text-lg text-ivory mt-5">தங்கை. J.P. லோகபரணிகா</p><p class="text-[11px] tracking-[0.15em] text-sandal/60 mt-1 uppercase font-serif">M.Com., B.Ed.,</p></div></div></div><p class="reveal max-w-2xl mx-auto text-center mt-16 font-serif italic text-lg text-sandal/80 leading-relaxed">"Our families warmly invite you to share in this sacred and joyous occasion."</p></section>`;

let html = fs.readFileSync('index.html', 'utf8');

html = html.replace(/<section class="py-28 px-6"><div class="text-center mb-20 reveal"><p class="font-script text-4xl md:text-5xl text-gold text-glow">with blessings of<\/p><h2 class="font-display text-4xl md:text-6xl gold-text mt-2">Our Families<\/h2>.*?<\/section>/s, newSection);

fs.writeFileSync('index.html', html, 'utf8');
console.log('Updated Families Section');
